# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fef9acb694468c99471e86d7a376474ebeb8a7a2a964dc7cc4fa387e4ce16f42c82ff62250bcbef0818a0501e53beb8cbd58802955be14c39de3e6297c11f56

test:
  secret_key_base: 2ca985107565cd9d966e4192b4f583a127b8b13a1baa8c68ab0a8bd1f0621f5f9881b4b42aeb70ea0b5b942763c31b09436e5514b4c7bfa1eeaccf25b39c1dcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
